# jekyll config
theme: minima
title: Curriculum vitae
author: Takuma Kurosawa
email: tennis.takumax@gmail.com
header_pages:
  - en.md
  - ja.md
disqus:
  shortname: comments
google_analytics: G-NRZH4MECQX
# social links
twitter_username: TakumaKurosawa
github_username:  TakumaKurosawa
linkedin_username: TakumaKurosawa
plugins:
  - jekyll-feed
  - jekyll-seo-tag
