# jekyll config
theme: minima
title: Curriculum vitae
author: Takuma Kurosawa
email: tennis.takumax@gmail.com
header_pages:
  - README.md
  - README_en.md
disqus:
  shortname: comments
# social links
twitter_username: TakumaKurosawa
github_username:  TakumaKurosawa
linkedin_username: TakumaKurosawa
plugins:
  - jekyll-feed
  - jekyll-seo-tag
